In [1]:
import numpy as np
import pandas as pd

In [6]:
from sklearn.cluster import KMeans
from sklearn.metrics.cluster import v_measure_score

In [7]:
data=pd.read_csv("Dataset_spine.csv")

In [8]:
data

Col1       Col2       Col3       Col4        Col5       Col6  \
0    63.027817  22.552586  39.609117  40.475232   98.672917  -0.254400   
1    39.056951  10.060991  25.015378  28.995960  114.405425   4.564259   
2    68.832021  22.218482  50.092194  46.613539  105.985135  -3.530317   
3    69.297008  24.652878  44.311238  44.644130  101.868495  11.211523   
4    49.712859   9.652075  28.317406  40.060784  108.168725   7.918501   
..         ...        ...        ...        ...         ...        ...   
305  47.903565  13.616688  36.000000  34.286877  117.449062  -4.245395   
306  53.936748  20.721496  29.220534  33.215251  114.365845  -0.421010   
307  61.446597  22.694968  46.170347  38.751628  125.670725  -2.707880   
308  45.252792   8.693157  41.583126  36.559635  118.545842   0.214750   
309  33.841641   5.073991  36.641233  28.767649  123.945244  -0.199249   

         Col7     Col8     Col9     Col10      Col11    Col12 Class_att  \
0    0.744503  12.5661  14.5386  15.30468 -28.658501  43.5123  Abnormal   
1    0.415186  12.8874  17.5323  16.78486 -25.530607  16.1102  Abnormal   
2    0.474889  26.8343  17.4861  16.65897 -29.031888  19.2221  Abnormal   
3    0.369345  23.5603  12.7074  11.42447 -30.470246  18.8329  Abnormal   
4    0.543360  35.4940  15.9546   8.87237 -16.378376  24.9171  Abnormal   
..        ...      ...      ...       ...        ...      ...       ...   
305  0.129744   7.8433  14.7484   8.51707 -15.728927  11.5472    Normal   
306  0.047913  19.1986  18.1972   7.08745   6.013843  43.8693    Normal   
307  0.081070  16.2059  13.5565   8.89572   3.564463  18.4151    Normal   
308  0.159251  14.7334  16.0928   9.75922   5.767308  33.7192    Normal   
309  0.674504  19.3825  17.6963  13.72929   1.783007  40.6049    Normal   

                                           Unnamed: 13  
0                                                  NaN  
1                                                  NaN  
2    Prediction is done by using binary classificat...  
3                                                  NaN  
4                                                  NaN  
..                                                 ...  
305                                                NaN  
306                                                NaN  
307                                                NaN  
308                                                NaN  
309                                                NaN  

[310 rows x 14 columns]

In [9]:
data_woc=data.iloc[:,0:12]
data_woc

Col1       Col2       Col3       Col4        Col5       Col6  \
0    63.027817  22.552586  39.609117  40.475232   98.672917  -0.254400   
1    39.056951  10.060991  25.015378  28.995960  114.405425   4.564259   
2    68.832021  22.218482  50.092194  46.613539  105.985135  -3.530317   
3    69.297008  24.652878  44.311238  44.644130  101.868495  11.211523   
4    49.712859   9.652075  28.317406  40.060784  108.168725   7.918501   
..         ...        ...        ...        ...         ...        ...   
305  47.903565  13.616688  36.000000  34.286877  117.449062  -4.245395   
306  53.936748  20.721496  29.220534  33.215251  114.365845  -0.421010   
307  61.446597  22.694968  46.170347  38.751628  125.670725  -2.707880   
308  45.252792   8.693157  41.583126  36.559635  118.545842   0.214750   
309  33.841641   5.073991  36.641233  28.767649  123.945244  -0.199249   

         Col7     Col8     Col9     Col10      Col11    Col12  
0    0.744503  12.5661  14.5386  15.30468 -28.658501  43.5123  
1    0.415186  12.8874  17.5323  16.78486 -25.530607  16.1102  
2    0.474889  26.8343  17.4861  16.65897 -29.031888  19.2221  
3    0.369345  23.5603  12.7074  11.42447 -30.470246  18.8329  
4    0.543360  35.4940  15.9546   8.87237 -16.378376  24.9171  
..        ...      ...      ...       ...        ...      ...  
305  0.129744   7.8433  14.7484   8.51707 -15.728927  11.5472  
306  0.047913  19.1986  18.1972   7.08745   6.013843  43.8693  
307  0.081070  16.2059  13.5565   8.89572   3.564463  18.4151  
308  0.159251  14.7334  16.0928   9.75922   5.767308  33.7192  
309  0.674504  19.3825  17.6963  13.72929   1.783007  40.6049  

[310 rows x 12 columns]

In [10]:
data_class=data.iloc[:,12]
data_class

0      Abnormal
1      Abnormal
2      Abnormal
3      Abnormal
4      Abnormal
         ...   
305      Normal
306      Normal
307      Normal
308      Normal
309      Normal
Name: Class_att, Length: 310, dtype: object

In [23]:
f1=data_woc['Col1'].values
f1

array([ 63.0278175 ,  39.05695098,  68.83202098,  69.29700807,
        49.71285934,  40.25019968,  53.43292815,  45.36675362,
        43.79019026,  36.68635286,  49.70660953,  31.23238734,
        48.91555137,  53.5721702 ,  57.30022656,  44.31890674,
        63.83498162,  31.27601184,  38.69791243,  41.72996308,
        43.92283983,  54.91944259,  63.07361096,  45.54078988,
        36.12568347,  54.12492019,  26.14792141,  43.58096394,
        44.5510115 ,  66.87921138,  50.81926781,  46.39026008,
        44.93667457,  38.66325708,  59.59554032,  31.48421834,
        32.09098679,  35.70345781,  55.84328595,  52.41938511,
        35.49244617,  46.44207842,  53.85479842,  66.28539377,
        56.03021778,  50.91244034,  48.332638  ,  41.35250407,
        40.55735663,  41.76773173,  55.28585178,  74.43359316,
        50.20966979,  30.14993632,  41.17167989,  47.65772963,
        43.34960621,  46.85578065,  43.20318499,  48.10923638,
        74.37767772,  89.68056731,  44.529051  ,  77.69

In [22]:
f2=data_woc['Col5'].values
f2

array([ 98.67291675, 114.4054254 , 105.9851355 , 101.8684951 ,
       108.1687249 , 130.3278713 , 120.5675233 , 117.2700675 ,
       125.0028927 ,  84.24141517, 108.6482654 , 120.0553988 ,
       119.321358  , 110.9666978 , 116.8065868 , 124.1158358 ,
       112.3094915 , 129.0114183 , 123.1592507 , 116.5857056 ,
       134.4610156 , 125.2127163 , 106.4243295 , 117.9808303 ,
       115.5771163 , 121.447011  , 125.2032956 , 109.271634  ,
       111.0729197 , 113.4770183 , 112.192804  ,  98.77454633,
       117.9803245 , 124.914118  , 119.3303537 , 113.8331446 ,
       132.264735  , 137.5406125 , 123.3118449 , 116.5597709 ,
       106.9388517 , 115.4814047 , 121.6709148 , 121.2196839 ,
       114.0231172 , 117.4222591 , 117.3846251 , 113.2666746 ,
       121.0462458 , 118.3633889 , 115.8770174 , 107.9493045 ,
       128.2925148 , 112.6841408 , 116.3778894 ,  98.24978071,
       112.7761866 , 116.2509174 , 124.8461088 , 124.0564518 ,
       143.5606905 , 129.9554764 , 134.7117723 , 114.81

In [21]:
f3=data_woc['Col9'].values
f3

array([14.5386, 17.5323, 17.4861, 12.7074, 15.9546, 12.0036, 10.7146,
        7.7676, 11.4234,  8.738 , 16.5097,  9.2589,  7.2049, 12.8127,
       18.6222, 19.1756, 16.8116, 18.6089, 17.9575, 12.4637, 16.8965,
       14.2195, 17.6891,  9.1019, 15.7438, 13.57  ,  8.6406, 17.97  ,
       10.2244,  8.2495,  7.2481,  7.4515, 13.8357,  7.5284,  8.3058,
        8.1003, 11.6395, 12.7274,  8.855 , 18.9113,  9.3239, 12.2285,
       11.5243, 10.2636, 12.2345, 18.6181, 11.0942, 16.7065,  8.2526,
        7.1646, 15.9714,  9.8062, 13.9907, 10.7071, 12.8432, 16.9817,
       14.2176, 14.6233, 16.2905, 14.1761, 15.3975, 18.6012, 13.7595,
       15.3209,  7.8098,  7.2405, 12.6737, 13.3444,  9.6504, 15.3124,
       18.3111,  8.7655, 17.7501,  8.6569,  7.4437,  9.5742, 17.3635,
       11.7696, 12.8779, 14.7577, 13.2216, 12.5946, 13.659 , 11.2339,
        8.383 , 15.0011, 15.0648, 18.1846,  8.7779, 16.7172, 11.2491,
       16.3676, 11.7878, 11.6354, 19.1837,  7.5666, 13.0551,  7.8697,
       15.0493, 10.3

In [24]:
x=np.array(list(zip(f1,f2,f3)))

In [25]:
x

array([[ 63.0278175 ,  98.67291675,  14.5386    ],
       [ 39.05695098, 114.4054254 ,  17.5323    ],
       [ 68.83202098, 105.9851355 ,  17.4861    ],
       [ 69.29700807, 101.8684951 ,  12.7074    ],
       [ 49.71285934, 108.1687249 ,  15.9546    ],
       [ 40.25019968, 130.3278713 ,  12.0036    ],
       [ 53.43292815, 120.5675233 ,  10.7146    ],
       [ 45.36675362, 117.2700675 ,   7.7676    ],
       [ 43.79019026, 125.0028927 ,  11.4234    ],
       [ 36.68635286,  84.24141517,   8.738     ],
       [ 49.70660953, 108.6482654 ,  16.5097    ],
       [ 31.23238734, 120.0553988 ,   9.2589    ],
       [ 48.91555137, 119.321358  ,   7.2049    ],
       [ 53.5721702 , 110.9666978 ,  12.8127    ],
       [ 57.30022656, 116.8065868 ,  18.6222    ],
       [ 44.31890674, 124.1158358 ,  19.1756    ],
       [ 63.83498162, 112.3094915 ,  16.8116    ],
       [ 31.27601184, 129.0114183 ,  18.6089    ],
       [ 38.69791243, 123.1592507 ,  17.9575    ],
       [ 41.72996308, 116.58570

In [27]:
kmean=KMeans(n_clusters=2,random_state=42)

In [29]:
model=kmean.fit(x)

/opt/anaconda3/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


In [30]:
cluster_labels=kmean.predict(x)

In [31]:
v=v_measure_score(cluster_labels,data_class)

In [32]:
v

0.1226702574168037

In [33]:
from sklearn.metrics import silhouette_score

In [37]:
sil=silhouette_score(x,cluster_labels,metric='euclidean',sample_size=len(data))

In [38]:
sil

0.40281106439818104