In [19]:
import numpy as np
arr= np.array([1,2,3,4])
print (arr)
type(arr)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3 4]
1
(4,)
4
int64


In [20]:
arr1= np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [21]:
arr2=np.array([[1,2,3,4],["iter",5,8,9]])
print(arr2)
type(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

[['1' '2' '3' '4']
 ['iter' '5' '8' '9']]
2
(2, 4)
8
<U21


In [7]:
print(arr.ndim)

1


In [25]:
arr= np.array([1,2,3,4],dtype=np.float64)
arrr= np.array([1,2,3,4])
print(arr,'\n',arrr)
print(arr.dtype,arrr.dtype)

[1. 2. 3. 4.] 
 [1 2 3 4]
float64 int64


In [26]:
arr= np.array([1,2,3,4],dtype=float)
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float64


In [27]:
arr=np.array([1,2,3,4,5])
float_arr=arr.astype(float)
print(float_arr)

[1. 2. 3. 4. 5.]
