In [5]:
marks=int(input("Enter Marks(0-100): "));
if(marks>100):
    print("Invalid marks")
elif(marks>=90):
    print("Grade A")
elif(marks>=75):
    print("Grade B")
elif(marks>=50):
    print("Grade C")
else:
    print("Failed")

Enter Marks(0-100): 101
Invalid marks


In [ ]:

def is_prime(num):
    if num==1:
        return False
    if num==2:
        return True
    for i in range(2,num):
        if(num%i==0):
            return False
        else:
            return True

num=int(input("Enter a number to check Prime: "));
is_prime(num)

In [21]:
import numpy as np

In [29]:
mat=np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
matA=mat[:,1]
matA

array([ 2,  6, 10, 14])

In [39]:
matB=mat[:,2]
matB

array([ 3,  7, 11, 15])